### ISSUE TITLE
Blender 3.6?

### ISSUE THREAD

**Issue by bencresty** [BlenderBoi/Frame_Ranger#6]
Hi,

I just saw there is a new release (3.1.1) which got published only 4 days ago. Yet to my surprise in the notes it says it's only supported up until blender 3.4 (which is old by now). 

Is this a typo? Are Blender 3.5 and 3.6 supported too?

Thanks!

**Comment by BlenderBoi** [comment]
Hi, while it is not tested, it should work

So far I have not receive any error reports

If you encounter any error or bug feel free to report to me and I will fix them

**Comment by bencresty** [comment]
Okay thanks
